cache: bundler
branches:
  only: 
    - gh-pages
    - /^release-.*/
language: ruby
rvm: 2.1
script: bundle exec jekyll build
group: stable
dist: trusty
os: linux
addons:
  artifacts:
    debug: true
    paths:
      - ./_site/
    target_paths: $TRAVIS_BRANCH
    working_dir: WORKING_DIR
    bucket: staging.topophiliapodcast.com
    s3_region: us-west-2
