cache: bundler
branches:
  only:
  - gh-pages
  - "/^release-.*/"
language: ruby
rvm: 2.1
script: bundle exec jekyll build
group: stable
dist: trusty
os: linux
deploy:
  provider: s3
  access_key_id: "$ARTIFACTS_KEY"
  secret_access_key: "$ARTIFACTS_SECRET"
  bucket: static.topophiliapodcast.com
  skip_cleanup: true
  upload-dir: "$TRAVIS_BRANCH"
  local-dir: _site
  on: 
    all_branches: true
